# Generated by Django 4.2.6 on 2023-10-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='media/qrcodes/'),
        ),
    ]
